[project]
name = "mazegen"
version = "0.1.0"
description = "A maze generation and solver tool built in python"
authors = [
    {name = "Bruno, Gildas"}
]
packages = [{include = "mazegen"}]
requires-python = ">=3.10"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
